AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  py-chat-v1

  Sample SAM Template for py-chat-v1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100
    MemorySize: 128

Resources:
  LangchainPythonFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: coffee-chatbot-python/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          MONOCLE_EXPORTER: s3
          MONOCLE_S3_BUCKET_NAME: YOUR_BUCKET_NAME
          OPENAI_API_KEY: YOUR_OPENAI_API_KEY
          MONOCLE_AWS_ACCESS_KEY_ID: MONOCLE_AWS_ACCESS_KEY_ID
          MONOCLE_AWS_SECRET_ACCESS_KEY: MONOCLE_AWS_SECRET_ACCESS_KEY
          MONOCLE_S3_KEY_PREFIX: monocle_trace_


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LangchainPythonFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LangchainPythonFunction.Arn
  LangchainPythonFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LangchainPythonFunctionRole.Arn
